name: NovaGuilds
main: co.marcin.novaguilds.NovaGuilds
author: Marcin Wieczorek
description: The best polish guilds plugin!
website: http://novaguilds.marcin.co/
version: 14
depend: [Vault]
softdepend: [BarAPI]
commands:
   novaguilds:
      description: Main NovaGuilds command
      usage: /novaguilds
      aliases: [ng]
   nga:
      description: Admin commands
      usage: /nga [cmd]
   guild:
      description: NovaGuilds guild command
      usage: /guild <cmd> [params]
      aliases: [g]
   guildmenu:
      description: NovaGuilds menu gui command
      usage: /guildmenu
      aliases: [gg]
   gi:
      description: NovaGuilds Guild Info
      usage: /gi <tag>
      aliases: [guildinfo]
   create:
      description: Create a guild
      usage: /create <tag> <name>
   nghome:
      description: Guilds home
      usage: /nghome
   abandon:
      description: Abandon guild
      usage: /abandon
   invite:
      description: Invite to guild
      usage: /invite <player>
   join:
      description: join a guild
      usage: /join [name]
   leave:
      description: leave the guild
      usage: /leave

permissions:
    novaguilds.region.create:
        default: op
    novaguilds.region.resize:
        default: op
    novaguilds.region.delete:
        default: op
    novaguilds.guild.home:
        default: op
    novaguilds.guild.create:
        default: op
    novaguilds.guild.abandon:
        default: op
    novaguilds.guild.info:
        default: op
    novaguilds.guild.leave:
        default: op
    novaguilds.tool.get:
        default: op
    novaguilds.tool.check:
        default: op
    novaguilds.admin.access:
        default: op
    novaguilds.admin.guild.access:
        default: op
    novaguilds.admin.guild.abandon:
        default: op
    novaguilds.admin.guild.tp:
        default: op
    novaguilds.admin.guild.tp.other:
        default: op
    novaguilds.admin.guild.money:
        default: op
    novaguilds.admin.guild.fullinfo:
        default: op
    novaguilds.admin.guild.setname:
        default: op
    novaguilds.admin.guild.settag:
        default: op
    novaguilds.admin.guild.kick:
        default: op
    novaguilds.admin.guild.list:
        default: op
    novaguilds.admin.region.delete:
        default: op
    novaguilds.admin.region.resize:
        default: op
    novaguilds.admin.region.bypass:
        default: op
    novaguilds.admin.region.bypass.other:
        default: op
    novaguilds.admin.region.list:
        default: op
    novaguilds.admin.region.tp:
        default: op
    novaguilds.admin.region.tp.other:
        default: op
    novaguilds.admin.reload:
        default: op
    novaguilds.admin.save:
        default: op
    novaguilds.admin.save.notify:
        default: op
    novaguilds.chat.notag:
        default: false
    novaguilds.group.admin:
        default: op
    novaguilds.group.default:
        default: true